### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ThanhPham1987** [yehengchen/SmartCar#5]
Hi yehengchen,
When i run data_preprocess.py. I face the issue: Traceback (most recent call last):
  File "data_preprocess.py", line 7, in <module>
    nrof_images_total,nrof_successfully_aligned=obj.collect_data()
  File "/home/thanhpham/PycharmProjects/FaceNet/FaceRecognition-FaceNet/preprocess.py", line 52, in collect_data
    img = misc.imread(image_path)
AttributeError: module 'scipy.misc' has no attribute 'imread'
Please give me some advice?
Best regards,
Thanks

**Comment by MikuuGithub** [comment]
> Hi yehengchen, When i run data_preprocess.py. I face the issue: Traceback (most recent call last): File "data_preprocess.py", line 7, in nrof_images_total,nrof_successfully_aligned=obj.collect_data() File "/home/thanhpham/PycharmProjects/FaceNet/FaceRecognition-FaceNet/preprocess.py", line 52, in collect_data img = misc.imread(image_path) AttributeError: module 'scipy.misc' has no attribute 'imread' Please give me some advice? Best regards, Thanks

可能是版本的问题，现在解决了吗？
